[package]
name = "nslauncher"
version = "0.1.0"
authors = ["belz, jeb"]
edition = "2018"

[dependencies]
dlopen = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
path-slash = "0.1.1"
tungstenite = "0.10"
tokio = { version = "0.2", features = ["full", "tcp"] }
futures-util = { version = "0.3.4", default-features = false, features = ["sink"] }
tokio-tungstenite = "0.10"
dirs = "2.0"
openssl = "0.10"
relm = "0.19.0"
relm-derive = "0.19.0"
jni = { git = "https://gitlab.com/nsl_team/jni-rs" }
launcher_api = {git = "https://gitlab.com/nsl_team/launcherapi"}

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]

[dependencies.gdk]
version = "0.12.1"

[profile.release]
opt-level = 'z'
lto = true