[package]
name = "launch_server"
version = "0.1.0"
authors = ["Jeb", "Belz"]
edition = "2018"


[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

actix = "0.9.0"
actix-codec = "0.2.0"
actix-web = "2.0.0"
actix-web-actors = "2.0.0"
actix-files = "0.2.1"
actix-rt = "1.0.0"

[profile.release]
lto = true
opt-level = 'z'