[package]
name = "nslauncher"
version = "0.1.0"
authors = ["Belz", "Jeb"]
edition = "2018"

[dependencies]
dlopen = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
path-slash = "0.1.1"
dirs = "2.0"
env_logger = "0.7.1"
url = "^2.0.0"
rand = "0.7.3"
base64 = "0.12.1"
rust-embed="5.5.1"
yarws = "0.3"
ecies-ed25519 = "0.3"
hyper = "0.13.6"
hyper-tls = "0.4.1"
futures = "0.3"
anyhow = "1.0.31"
notify = "5.0.0-pre.2"
async-trait = "0.1"
once_cell = "1.5"
uuid = "0.8"
log = "0.4"

[dependencies.web-view]
version = "0.6.2"
git = "https://gitlab.com/nsl_team/web-view"
branch = "frameless"

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.launcher_api]
path = "../launcherapi"

[dependencies.jni]
git = "https://gitlab.com/nsl_team/jni-rs"
branch = "dynamic"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'