on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Install system dependencies
        run: |
          sudo apt update -q
          sudo apt install -y libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev libappindicator3-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}